### ISSUE TITLE
Should we support CommonJS?

### ISSUE THREAD

**Issue by cognitom** [cognitom/es-http-error#2]
At this point, this library is written / provided in pure ES Modules.
We can simply generate CommonJS files via Rollup. But, to make *transitional* library, we should consider `.mjs` extension for compatibility. Any idea?

**Comment by rallu** [comment]
Maybe keep this library looking towards future only? So only .mjs? 

Everyone has their own build processes and I would argue that there is no need to provide old type of builds.

**Comment by cognitom** [comment]
Yeah, I think so, too. We will keep this library *pure*. Let's think about changing the extention in the near future.

I'd like to keep open this issue for a while. If someone has any idea, feel free to comment here 😄

**Comment by cognitom** [comment]
I've changed my mind a little, and I started thinking that I'd like to use it on serverside, too.
As a compromise, I've decided to add a CJS version, but English only. So, now it works on Node.js from v1.2.1. Thanks!
